
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postpotato1
      POSTGRES_DB: university_registration
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
      RUST_BACKTRACE: 1
      DATABASE_URL: postgres://postgres:postpotato1@db/university_registration
      RUST_LOG: debug
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  pgdata:

